os: linux
dist: focal
language: php
git:
  depth: false

stage: test
env:
  - FRAMEWORK="laravel/framework:8.*"
php:
  - '7.4'
  - '8.0'
workspaces:
  create:
    name: coverage-report
    paths:
      - coverage-report.clover
install:
  - pecl install pcov
  - composer require ${FRAMEWORK}
script:
  - php -d pcov.enabled=1 vendor/bin/phpunit --coverage-clover=coverage-report.clover

jobs:
  include:
    - stage: deploy
      name: "Sonar Analyze"
      php:
        - '7.4'
      env:
        - FRAMEWORK=none
      workspaces:
        use: coverage-report
      addons:
        sonarcloud:
          organization: "tochka-developers"
          token:
            secure: "pDZM23SiuMMj1nsd/ZBW4c9Y96bv1fQ6p7+Aja2vdGheqEsbCNQqQOPnjq0AVKdFou+z2JeMo+svpbBc5i2hGNn+tSEVwQmp7OT8KXmXJNRp1COrM/4DI7vQjnq2TUjrrDobDvbIwFiZawcW6k8EwFJVe2dPFrhzVz95KGXh1zk8MsSNWWUWgyxOGWq8yjCOLvSW4Nzs/3GAWjEiMJzzqxkKmdys6r2O9v7lud3tBQOQgKPgba8fDM/LCoOIItGRDyZUYT/Y74nUsAB+B0H1PuWtZ2ZLMTbXu1iDmVlQf/PxWvZPhw9PRmncaE7O3nM3fj7Zmhkv12BlGt4FPHpYJqBBIls+rdmC8ng5/R1+zrlR3Pq1DyXzb7FBAFQhk3MpKfKhRz2h2qreTALnp/zF51GOd7mytISoJWOUlzQxoEks6Q+vFRsDQ33NGH/lLIrOClH/GIg10SdeERlLnMCfUSF8fBO6XCagthrI5N4AvWJ7Hw84SR9JXW/erqfTLK3On1CHGQxaQeYGZWWjgtpJFPLJVSyatsnE6wa2yDsy6QTVWICPlb9Gv5o89rWYPr00RfbnMTTb4XCVxkkFdsJRgfAKFNm+Ms9fRWZ/hwoal2Dhi2XtraAAKxN2m5wYNxPqEWi71Qd+p/UJnC2OEF7sGmAwd8faiXK54iuaEfx5PRE="
      install: skip
      script: sonar-scanner

