dist: trusty
language: php
php:
  - '7.3'
  - '7.4'
install:
  - composer install
addons:
  sonarcloud:
    organization: "tochka-developers"
    token:
      secure: "4c9Mm1rmEPzhaAhkbAOIa70IHVKVnaaJGgUzh9TVE7+PPRBYaQsTMa/AVbQb3184+OudzUR+51kJcJF+B38s2L6OTpsVKtm7bSQoED67GZIbuWr3UPseuYtlBI1n7/osAvKW87laacWxgX4VJZTJ5E5YO4fm2IaK3LODi9MH+9z3O1Yu25WGj15wdD4DgL5YznXYym9RA2rTg9rSv0DxcbYAir9rH9soWGs1dv+9gaYCtVy1+/hpLJldM6WlWGwA0AK7FzG85Y6h8KdgzwM31++OGdccX9JyONfR2ysUv5wQUEzU4tIlpCRWNFRv/7s/1ypfv+ZEtM4glcwceR9GD/bEOkzp9nsCjhySs34U0XNhkWSUKvhGXLPdOiIFhsSFq7WjCDl6x6LC3w3jBEqPbTwcaMptgpfAXCfI8pPt3t/XO98+TyeGElq2Ohl6pOQ3W9J9UN7d2olxm3Cj4lt+H4xloGablS7Rna0mxw59IZdyP2ky4tXMSWjnAVac3hVrhU6zQZu+2WIbROPQI6aF8/KdzsU/v0Gp/C6Ic7BvE67DdNX8NsyUXSC3zRjSGE0YHYP+P5e17UXTvsnYa74Gu8PPjzZItLaAr0jDWxo/CTJswQvACxl597y1FenfQ2GOUotMhhJtwUQQVmLYw5QA7bOzHSSCGG9l6SOV4bisaCo="
git:
  depth: false
script:
  - vendor/bin/phpunit --coverage-clover=coverage-report.clover --log-junit=test-report.xml
  - sonar-scanner
