dist: trusty
language: php
php:
  - '7.3'
  - '7.4'
install:
  - composer install
addons:
  sonarcloud:
    organization: "tochka-developers"
    token:
      secure: "ek17Nu/1EnHKEe4cAvYwVI5JEiNz1OKgl2QrP7Y6r4tq26kWg7WtLuO6nOW3SWkWyw5eZM/SsTSdi71PsRhdXXCx7/Zqhtnl+SEx1ucMvGw14piOUR5p5NC0684+TzLMh2gaMOipg7or9YQiF8hVWpUWC9sl20H4PbAJIpdVaSuwQ7Qp3KF52x6ckJRgBIYGyj7t2apmKeiIgDJaoPYKnnmb9GCfDyBhVk7ade/ANAYWirsE0h3ZJ89PMfF4GJvQ0tEC7FEWsF5hsot+B2DgQ0E7JfyvEnYmmYlGSk6ZmBco3eF+VQB7iNdxYnS/p5jP5bux8esytaEVwe2YkNTcGELhbetJUGIEgPr6hlCUBAHXe8zI/QjOrNgwFJF9+6YjpDPI19lc0CgN1252gleZBDeeckPsTzhr9UhrmWaXfFDwl6gWTP7I9EEJGI2YTfJMBdhqSB4xPJGccHbMY6YL46FCDJ9+H+neBOp4GkcCKOMmcY5kUUyaqlSUFjlpJJKVyfmG6+AnqM+23dwVAjRGigEB4Wt4CZKoX44mKps5tSQpL8lxPJ3Pw7EY/ksa6khBaszNJt+qEUtLHFZrJyfAy9BDX/w+Zdg96JqEgzi20l0QSv+u+2tgT60A840yVB4oZlU3KfadwxMfSThfKaiixeV/Xf8F3E2nWDOyFIsTrU4="
git:
  depth: false
script:
  - vendor/bin/phpunit --coverage-clover=coverage-report.clover --log-junit=test-report.xml
  - sonar-scanner
